#!/bin/bash

cd $FIELDDB_HOME/AuthenticationWebService
bash switch_to_producti.sh 

forever \
start \
-al $FIELDDB_HOME/logs/fielddbauth.log \
-ao $FIELDDB_HOME/logs/fielddbauthout.log \
-ae $FIELDDB_HOME/logs/fielddbautherr.log \
service.js
