#!/bin/bash

cd $FIELDDB_HOME/AuthenticationWebService
NODE_DEPLOY_TARGET="production"

$FIELDDB_HOME/AuthenticationWebService/node_modules/forever/bin/forever \
start \
-al $FIELDDB_HOME/logs/fielddbauth.log \
-ao $FIELDDB_HOME/logs/fielddbauthout.log \
-ae $FIELDDB_HOME/logs/fielddbautherr.log \
service.js
